"""
Django settings for am_tools project.
Generated by 'django-admin startproject' using Django 1.9.5.
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i^t5wjmhl9%hsasd2367dadasd234hh546gfhfg6546j546dfgdfg345l;juja^d-\
e%199-5ai5qo8w5_rd7dng00oix=#x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'selector',
    'common_modules',
    'builds',
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'am_tools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'am_tools.wsgi.application'


# =======================   TO-CHANGE SECTION   ============================= #
#   Please, maintain tags in comments for auto-deploy tool.
#   This tool automatically uncomment MIGRATION section
#   to make a DB migrations before deploy and PRODUCTION
#   section, while deploying. Others sections are commented
#   in this time.


# Settings for developing on alexey.sychov localhost
# ----------------- <LOCALHOST> ------------------- #
##DATABASES = {
##    'default': {
##        'ENGINE': 'django.db.backends.mysql',
##        'NAME': 'am',
##        'USER': 'am',
##        'PASSWORD': 'pass',
##        'HOST': '127.0.0.1',
##        'PORT': '3306',
##    }
##}
##
##MEDIA_ROOT = 'd:\\temp\\'
##HOST_URL = r'http://localhost:8000'
# ----------------- </LOCALHOST> ------------------- #


# Settings used for database models migration on production
# --------------------- <MIGRATION> ------------------------ #
##DATABASES = {
##    'default': {
##        'ENGINE': 'django.db.backends.mysql',
##        'NAME': 'am',
##        'USER': 'toor',
##        'PASSWORD': 'dhg34sadf23D',
##        'HOST': '10.136.4.161',
##        'PORT': '3306',
##    }
##}
##
##MEDIA_ROOT = 'd:/temp/'
##HOST_URL = 'NO HOST, MAN!!!! IF YOU SEE THAT, SOMETHING STRANGE IS GOING ON!'
# --------------------- </MIGRATION> -------------------------- #


# Settings used for virtual host deployment
# ------------------- <VIRTUAL HOST> ------------------------ #
##DATABASES = {
##    'default': {
##        'ENGINE': 'django.db.backends.mysql',
##        'NAME': 'test',
##        'USER': 'virtualka',
##        'PASSWORD': 'virt',
##        'HOST': '10.60.15.250',
##        'PORT': '3306',
##    }
##}
##
##MEDIA_ROOT = r'/media/mydata/media/'
##HOST_URL = r'http://10.60.15.250'
# ------------------- </VIRTUAL HOST> ------------------------ #


# Production settings
# ------------------- <PRODUCTION> ------------------------ #
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'am',
        'USER': 'am',
        'PASSWORD': 'dhg34sadf23D',
        'HOST': 'am-kha-kubedb-mysql',
        'PORT': '3306',
    }
}

MEDIA_ROOT = r'/opt/data/media'
HOST_URL = 'https://am-kha.kha-am-staging.k01.gameloft.org/'
# ------------------- </PRODUCTION> ------------------------ #

# ========================= END OF CHANGE SECTION =========================== #


AUTH_PASSWORD_VALIDATORS = [
    {
     'NAME':
     'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
     'NAME':
     'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
     'NAME':
     'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
     'NAME':
     'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = False

LOGIN_URL = '/index'

STATIC_URL = '/static/'

STATIC_ROOT = r'd:/Programmirovanie/projects/asphalt_manager/sync-to-webtools/src/static/'

MEDIA_URL = '/media/'

# OTHER SETTINGS

ERROR_MAIL = 'georgiy.voronov@gameloft.com'
##SMTP_SERVER = 'smtprelay.mdc.gameloft.org'
SMTP_SERVER = 'relay.gameloft.org'

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/wasm", ".wasm", True)





